/* Auto-generated by generate-wrappers.py script. Do not modify */

#if defined(__arm__) || defined(__aarch64__) || defined(__gptx__)

#include <q8avgpool/mp8x9p8q-neon.c>
#endif /* defined(__arm__) || defined(__aarch64__) */
