/* Auto-generated by generate-wrappers.py script. Do not modify */

#if defined(__arm__) || defined(__aarch64__) || defined(__gptx__)

#include <x8zip/x4-neon.c>
#endif /* defined(__arm__) || defined(__aarch64__) */
